language: minimal

services: docker

before_install:
  - docker -v && docker-compose -v

install:
  - docker-compose -f project/udacity-deployment/docker/docker-compose-build.yaml build --parallel
  - docker tag reverseproxy reverseproxy:v1
  - docker tag udagram-api-user udagram-api-user:v1
  - docker tag udagram-api-feed udagram-api-feed:v1
  - docker tag udagram-frontend udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push reverseproxy:v1
  - docker push udagram-api-user:v1
  - docker push udagram-api-feed:v1
  - docker push udagram-frontend:v1

